version: '3'
services:

  mp-redis:
    container_name: mp-redis
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - test-network

  mp-mongodb:
    container_name: mp-mongodb
    image: mongo:3.6
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - test-network

volumes:
  mongo-data:
networks:
  test-network: